### ISSUE TITLE
How to avoid the problem that attention goes to 1 and the network doesn't work？

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [albertpumarola/GANimation#63]
As mentioned above， thank you for reply

**Comment by albertpumarola** [comment]
This is prevented by penalizing the norm of the attention, its one of the terms of the attention loss. If the attention is saturating to 1 with the proposed hyperparameters it may be an indication that something is wrong in the data. This being said, if you augment the weight of this specific term (not the full attention loss, only the norm term) it will decrease. But be careful, if you augment it too much instead of saturating to 1 it will go to 0 which is also not desired. The optimal weight is that such that it will keep the attention around 0.5

**Comment by ZHANG-SHI-CHANG** [comment]
> This is prevented by penalizing the norm of the attention, its one of the terms of the attention loss. If the attention is saturating to 1 with the proposed hyperparameters it may be an indication that something is wrong in the data. This being said, if you augment the weight of this specific term (not the full attention loss, only the norm term) it will decrease. But be careful, if you augment it too much instead of saturating to 1 it will go to 0 which is also not desired. The optimal weight is that such that it will keep the attention around 0.5

In fact, I use CelebA dataset to test the method, attention is easy saturating to 1  with your attention loss, maybe it can work if I keep the attention to 0.5 by L1 Mandatory?

**Comment by albertpumarola** [comment]
I prefer the model to decide the specific range of values rather than forcing one, but as a last resource its a totally valid option

**Comment by ZHANG-SHI-CHANG** [comment]
> I prefer the model to decide the specific range of values rather than forcing one, but as a last resource its a totally valid option

Thank you for your reply, I will try it according to your suggestion, and will communicate with you after the results^_^

**Comment by ZHANG-SHI-CHANG** [comment]
> I prefer the model to decide the specific range of values rather than forcing one, but as a last resource its a totally valid option

By the way, have you tried Two Time-Scale Update Rule in this task?

**Comment by albertpumarola** [comment]
No... but it would definitely be a nice thing to try.

**Comment by joyyang1997** [comment]
@ZHANG-SHI-CHANG  Hi, I met the same question as you, do you have any advice for me?
Many thanks!
