### ISSUE TITLE
Attention loss convergence

### ISSUE THREAD

**Issue by affromero** [albertpumarola/GANimation#9]
1. Attention loss goes directly to zero after a few iterations, so the mask is zero, then the generator ignores the real image here https://github.com/albertpumarola/GANimation/blob/master/models/ganimation.py#L228. Regularizing the mask prevents the saturation to 1, but what about going to zero?

2. What is the purpose of https://github.com/albertpumarola/GANimation/blob/master/models/ganimation.py#L404-L405? As far as I can see `saturate=True` is never called.

**Comment by albertpumarola** [comment]
Without the regularisation saturating to 1 is easy, but saturating to 0 is hard. 1 is easy because all the losses would be 0 except the AUs estimator. Saturating to 0 would only have such a low total loss if the regressor was almost perfect (hard).

The saturate function is part of an experiment which did not make it to the paper but I'm still working on it.
